import {
  Paper,
  Grid,
  TextField,
  Button,
  Typography,
  Link,
} from "@mui/material";
import React, { useContext, useEffect, useState } from "react";

import { Form, Formik } from "formik";
import { useNavigate } from "react-router-dom";
import * as Yup from "yup";
import ActiveUserContext from "../../../Contexts/ActiveUserContext";
import UserService from "../../../Services/UserService";

const loginValidationSchema = Yup.object().shape({
  email: Yup.string()
    .email("Invalid email address")
    .required("Email is required"),
  password: Yup.string().required("Password is required"),
});

const signupValidationSchema = Yup.object().shape({
  email: Yup.string()
    .email("Invalid email address")
    .required("Email is required"),
  password: Yup.string()
    .min(4, "Password must be at least 4 characters")
    .required("Password is required"),
  firstName: Yup.string().required("First name is required"),
  lastName: Yup.string().required("Last name is required"),
  address: Yup.string(),

  birthDate: Yup.string()
    .required("Birth date is required")
    .test("is-13", "You must be at least 13 years old", (value) => {
      if (!value) return false;

      const birth = new Date(value);
      const today = new Date();

      let age = today.getFullYear() - birth.getFullYear();
      const monthDiff = today.getMonth() - birth.getMonth();

      if (
        monthDiff < 0 ||
        (monthDiff === 0 && today.getDate() < birth.getDate())
      ) {
        age--;
      }

      return age >= 13;
    }),

  profileImageUrl: Yup.string(),
});

const Login = () => {
  const [isSignup, setIsSignup] = useState(false);
  const paperStyle = {
    padding: 20,
    height: isSignup ? "auto" : "70vh",
    width: 280,
    margin: "20px auto",
  };
  const btnstyle = { margin: "8px 0" };
  const navigate = useNavigate();
  const { login } = useContext(ActiveUserContext);

  const handleLoginSubmit = (values: { email: string; password: string }) => {
    login(values.email.toLowerCase(), values.password)
      .then(() => {
        console.log(values);
        navigate("/user");
      })
      .catch((error) => {
        if (
          (typeof error.response !== "undefined" &&
            error.response.status === 401) ||
          error.response.status === 403
        ) {
          alert("invalid login");
        } else {
          alert("login Error");
        }
      });
  };

  const handleSignupSubmit = (values: {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    address: string;
    birthDate: string;
    profileImageUrl: string;
  }) => {
    const userData = {
      id: "", // will be generated by backend
      email: values.email.toLowerCase(),
      password: values.password,
      firstName: values.firstName,
      lastName: values.lastName,
      roles: [],
      profile: {
        address: values.address || "",
        birthDate: values.birthDate || "",
        profileImageUrl: values.profileImageUrl || "",
      },
    };

    UserService.addUser(userData)
      .then(() => {
        alert("Signup successful! Please login.");
        setIsSignup(false);
      })
      .catch((error) => {
        if (typeof error.response !== "undefined") {
          if (error.response.status === 409) {
            alert("Email already exists");
          } else if (error.response.status === 400) {
            alert("Invalid data provided");
          } else {
            alert("Signup Error");
          }
        } else {
          alert("Signup Error");
        }
      });
  };
  return (
    <Grid>
      <Paper elevation={10} style={paperStyle}>
        <Grid>
          <h2>{isSignup ? "Sign Up" : "Sign In"}</h2>
          {!isSignup && (
            <>
              <p>Default login:</p>
              <p>email: admin@example.com</p>
              <p>pw: 1234</p>
            </>
          )}
        </Grid>

        {!isSignup ? (
          <Formik
            initialValues={{
              email: "",
              password: "",
            }}
            enableReinitialize
            validationSchema={loginValidationSchema}
            onSubmit={handleLoginSubmit}
            validateOnChange
          >
            {(props) => (
              <Form onSubmit={props.handleSubmit}>
                <TextField
                  label="email"
                  id="email"
                  placeholder="Enter email"
                  fullWidth
                  required
                  autoFocus
                  onChange={props.handleChange}
                  onBlur={props.handleBlur}
                  value={props.values.email}
                  error={props.touched.email && !!props.errors.email}
                  helperText={props.touched.email && props.errors.email}
                  margin="normal"
                />

                <TextField
                  id="password"
                  label="password"
                  placeholder="Enter password"
                  type="password"
                  fullWidth
                  required
                  onChange={props.handleChange}
                  onBlur={props.handleBlur}
                  value={props.values.password}
                  error={props.touched.password && !!props.errors.password}
                  helperText={props.touched.password && props.errors.password}
                  margin="normal"
                />

                <Button
                  type="submit"
                  color="primary"
                  variant="contained"
                  style={btnstyle}
                  fullWidth
                >
                  Sign in
                </Button>
                <Button
                  type="button"
                  color="inherit"
                  variant="contained"
                  style={btnstyle}
                  fullWidth
                  onClick={() => setIsSignup(true)}
                >
                  Switch to Signup
                </Button>
              </Form>
            )}
          </Formik>
        ) : (
          <Formik
            initialValues={{
              email: "",
              password: "",
              firstName: "",
              lastName: "",
              address: "",
              birthDate: "",
              profileImageUrl: "",
            }}
            enableReinitialize
            validationSchema={signupValidationSchema}
            onSubmit={handleSignupSubmit}
            validateOnChange
          >
            {(props) => (
              <Form onSubmit={props.handleSubmit}>
                <TextField
                  label="Email"
                  id="email"
                  placeholder="Enter email"
                  fullWidth
                  required
                  autoFocus
                  onChange={props.handleChange}
                  onBlur={props.handleBlur}
                  value={props.values.email}
                  error={props.touched.email && !!props.errors.email}
                  helperText={props.touched.email && props.errors.email}
                  margin="normal"
                />

                <TextField
                  id="password"
                  label="Password"
                  placeholder="Enter password"
                  type="password"
                  fullWidth
                  required
                  onChange={props.handleChange}
                  onBlur={props.handleBlur}
                  value={props.values.password}
                  error={props.touched.password && !!props.errors.password}
                  helperText={props.touched.password && props.errors.password}
                  margin="normal"
                />

                <TextField
                  id="firstName"
                  label="First Name"
                  placeholder="Enter first name"
                  fullWidth
                  required
                  onChange={props.handleChange}
                  onBlur={props.handleBlur}
                  value={props.values.firstName}
                  error={props.touched.firstName && !!props.errors.firstName}
                  helperText={props.touched.firstName && props.errors.firstName}
                  margin="normal"
                />

                <TextField
                  id="lastName"
                  label="Last Name"
                  placeholder="Enter last name"
                  fullWidth
                  required
                  onChange={props.handleChange}
                  onBlur={props.handleBlur}
                  value={props.values.lastName}
                  error={props.touched.lastName && !!props.errors.lastName}
                  helperText={props.touched.lastName && props.errors.lastName}
                  margin="normal"
                />

                <TextField
                  id="address"
                  label="Address"
                  placeholder="Enter address (optional)"
                  fullWidth
                  onChange={props.handleChange}
                  onBlur={props.handleBlur}
                  value={props.values.address}
                  error={props.touched.address && !!props.errors.address}
                  helperText={props.touched.address && props.errors.address}
                  margin="normal"
                />

                <TextField
                  id="birthDate"
                  label="Birth Date"
                  type="date"
                  fullWidth
                  InputLabelProps={{
                    shrink: true,
                  }}
                  onChange={props.handleChange}
                  onBlur={props.handleBlur}
                  value={props.values.birthDate}
                  error={props.touched.birthDate && !!props.errors.birthDate}
                  helperText={props.touched.birthDate && props.errors.birthDate}
                  margin="normal"
                />

                <TextField
                  id="profileImageUrl"
                  label="Profile Image Url"
                  placeholder="Enter profile image url (optional)"
                  fullWidth
                  onChange={props.handleChange}
                  onBlur={props.handleBlur}
                  value={props.values.profileImageUrl}
                  error={
                    props.touched.profileImageUrl &&
                    !!props.errors.profileImageUrl
                  }
                  helperText={
                    props.touched.profileImageUrl &&
                    props.errors.profileImageUrl
                  }
                  margin="normal"
                />

                <Button
                  type="submit"
                  color="primary"
                  variant="contained"
                  style={btnstyle}
                  fullWidth
                >
                  Sign Up
                </Button>
                <Button
                  type="button"
                  color="inherit"
                  variant="contained"
                  style={btnstyle}
                  fullWidth
                  onClick={() => setIsSignup(false)}
                >
                  Switch to Sign In
                </Button>
              </Form>
            )}
          </Formik>
        )}

        {!isSignup && (
          <Typography>
            <Link href="#">Forgot password ?</Link>
          </Typography>
        )}
      </Paper>
    </Grid>
  );
};

export default Login;
